// Auto-generated by FORGE - DO NOT EDIT

#![allow(
    dead_code,
    unused_imports,
    clippy::redundant_field_names,
    clippy::too_many_arguments
)]

use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Attachment {
    pub id: String,
    pub task_id: String,
    pub user_id: String,
    pub filename: String,
    pub content_type: String,
    pub size_bytes: i64,
    pub storage_key: String,
    pub display: AttachmentDisplay,
    pub created_at: String,
}

impl Attachment {
    pub fn new(
        id: impl Into<String>,
        task_id: impl Into<String>,
        user_id: impl Into<String>,
        filename: impl Into<String>,
        content_type: impl Into<String>,
        size_bytes: i64,
        storage_key: impl Into<String>,
        display: AttachmentDisplay,
        created_at: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            task_id: task_id.into(),
            user_id: user_id.into(),
            filename: filename.into(),
            content_type: content_type.into(),
            size_bytes: size_bytes,
            storage_key: storage_key.into(),
            display: display,
            created_at: created_at.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthResponse {
    pub access_token: String,
    pub refresh_token: String,
    pub viewer: Viewer,
}

impl AuthResponse {
    pub fn new(
        access_token: impl Into<String>,
        refresh_token: impl Into<String>,
        viewer: Viewer,
    ) -> Self {
        Self {
            access_token: access_token.into(),
            refresh_token: refresh_token.into(),
            viewer: viewer,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CreateAttachmentInput {
    pub task_id: String,
    pub filename: String,
    pub content_type: String,
    pub size_bytes: i64,
}

impl CreateAttachmentInput {
    pub fn new(
        task_id: impl Into<String>,
        filename: impl Into<String>,
        content_type: impl Into<String>,
        size_bytes: i64,
    ) -> Self {
        Self {
            task_id: task_id.into(),
            filename: filename.into(),
            content_type: content_type.into(),
            size_bytes: size_bytes,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CreateFieldDefinitionInput {
    pub key: String,
    pub value_type: FieldValueType,
    pub color: Option<String>,
    pub options: Option<Vec<String>>,
}

impl CreateFieldDefinitionInput {
    pub fn new(key: impl Into<String>, value_type: FieldValueType) -> Self {
        Self {
            key: key.into(),
            value_type: value_type,
            color: None,
            options: None,
        }
    }

    pub fn color(mut self, color: impl Into<String>) -> Self {
        self.color = Some(color.into());
        self
    }

    pub fn options(mut self, options: Vec<String>) -> Self {
        self.options = Some(options);
        self
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CreateTaskInput {
    pub title: String,
    pub description: Option<String>,
    pub status: Option<TaskStatus>,
}

impl CreateTaskInput {
    pub fn new(title: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            description: None,
            status: None,
        }
    }

    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    pub fn status(mut self, status: TaskStatus) -> Self {
        self.status = Some(status);
        self
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeleteAttachmentInput {
    pub id: String,
}

impl DeleteAttachmentInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeleteFieldDefinitionInput {
    pub id: String,
}

impl DeleteFieldDefinitionInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeleteTaskInput {
    pub id: String,
}

impl DeleteTaskInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FieldDefinition {
    pub id: String,
    pub user_id: String,
    pub key: String,
    pub value_type: FieldValueType,
    pub color: Option<String>,
    pub options: Option<Vec<String>>,
    pub position: i32,
    pub created_at: String,
}

impl FieldDefinition {
    pub fn new(
        id: impl Into<String>,
        user_id: impl Into<String>,
        key: impl Into<String>,
        value_type: FieldValueType,
        position: i32,
        created_at: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            user_id: user_id.into(),
            key: key.into(),
            value_type: value_type,
            position: position,
            created_at: created_at.into(),
            color: None,
            options: None,
        }
    }

    pub fn color(mut self, color: impl Into<String>) -> Self {
        self.color = Some(color.into());
        self
    }

    pub fn options(mut self, options: Vec<String>) -> Self {
        self.options = Some(options);
        self
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FocusTaskInput {
    pub id: String,
}

impl FocusTaskInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetTaskInput {
    pub id: String,
}

impl GetTaskInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListAttachmentsInput {
    pub task_id: String,
}

impl ListAttachmentsInput {
    pub fn new(task_id: impl Into<String>) -> Self {
        Self {
            task_id: task_id.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListTaskFieldsInput {
    pub task_id: String,
}

impl ListTaskFieldsInput {
    pub fn new(task_id: impl Into<String>) -> Self {
        Self {
            task_id: task_id.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LoginInput {
    pub email: String,
    pub password: String,
}

impl LoginInput {
    pub fn new(email: impl Into<String>, password: impl Into<String>) -> Self {
        Self {
            email: email.into(),
            password: password.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LogoutInput {
    pub refresh_token: String,
}

impl LogoutInput {
    pub fn new(refresh_token: impl Into<String>) -> Self {
        Self {
            refresh_token: refresh_token.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PublicUser {
    pub id: String,
    pub email: String,
    pub name: String,
}

impl PublicUser {
    pub fn new(id: impl Into<String>, email: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            email: email.into(),
            name: name.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RefreshInput {
    pub refresh_token: String,
}

impl RefreshInput {
    pub fn new(refresh_token: impl Into<String>) -> Self {
        Self {
            refresh_token: refresh_token.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RefreshResponse {
    pub access_token: String,
    pub refresh_token: String,
}

impl RefreshResponse {
    pub fn new(access_token: impl Into<String>, refresh_token: impl Into<String>) -> Self {
        Self {
            access_token: access_token.into(),
            refresh_token: refresh_token.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RegisterInput {
    pub name: String,
    pub email: String,
    pub password: String,
}

impl RegisterInput {
    pub fn new(
        name: impl Into<String>,
        email: impl Into<String>,
        password: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            email: email.into(),
            password: password.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RemoveTaskFieldInput {
    pub task_id: String,
    pub field_id: String,
}

impl RemoveTaskFieldInput {
    pub fn new(task_id: impl Into<String>, field_id: impl Into<String>) -> Self {
        Self {
            task_id: task_id.into(),
            field_id: field_id.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ReorderTaskInput {
    pub id: String,
    pub status: TaskStatus,
    pub position: i32,
}

impl ReorderTaskInput {
    pub fn new(id: impl Into<String>, status: TaskStatus, position: i32) -> Self {
        Self {
            id: id.into(),
            status: status,
            position: position,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetTaskFieldInput {
    pub task_id: String,
    pub field_id: String,
    pub value: String,
}

impl SetTaskFieldInput {
    pub fn new(
        task_id: impl Into<String>,
        field_id: impl Into<String>,
        value: impl Into<String>,
    ) -> Self {
        Self {
            task_id: task_id.into(),
            field_id: field_id.into(),
            value: value.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Task {
    pub id: String,
    pub user_id: String,
    pub title: String,
    pub description: String,
    pub status: TaskStatus,
    pub time_spent_secs: i64,
    pub position: i32,
    pub due_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

impl Task {
    pub fn new(
        id: impl Into<String>,
        user_id: impl Into<String>,
        title: impl Into<String>,
        description: impl Into<String>,
        status: TaskStatus,
        time_spent_secs: i64,
        position: i32,
        created_at: impl Into<String>,
        updated_at: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            user_id: user_id.into(),
            title: title.into(),
            description: description.into(),
            status: status,
            time_spent_secs: time_spent_secs,
            position: position,
            created_at: created_at.into(),
            updated_at: updated_at.into(),
            due_at: None,
        }
    }

    pub fn due_at(mut self, due_at: impl Into<String>) -> Self {
        self.due_at = Some(due_at.into());
        self
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TaskField {
    pub id: String,
    pub task_id: String,
    pub field_id: String,
    pub value: String,
}

impl TaskField {
    pub fn new(
        id: impl Into<String>,
        task_id: impl Into<String>,
        field_id: impl Into<String>,
        value: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            task_id: task_id.into(),
            field_id: field_id.into(),
            value: value.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UnfocusTaskInput {
    pub id: String,
}

impl UnfocusTaskInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdateFieldDefinitionInput {
    pub id: String,
    pub key: Option<String>,
    pub color: Option<String>,
    pub options: Option<Vec<String>>,
    pub position: Option<i32>,
}

impl UpdateFieldDefinitionInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            key: None,
            color: None,
            options: None,
            position: None,
        }
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn color(mut self, color: impl Into<String>) -> Self {
        self.color = Some(color.into());
        self
    }

    pub fn options(mut self, options: Vec<String>) -> Self {
        self.options = Some(options);
        self
    }

    pub fn position(mut self, position: i32) -> Self {
        self.position = Some(position);
        self
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdateTaskInput {
    pub id: String,
    pub title: Option<String>,
    pub description: Option<String>,
    pub status: Option<TaskStatus>,
    pub due_at: Option<Option<String>>,
}

impl UpdateTaskInput {
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            title: None,
            description: None,
            status: None,
            due_at: None,
        }
    }

    pub fn title(mut self, title: impl Into<String>) -> Self {
        self.title = Some(title.into());
        self
    }

    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    pub fn status(mut self, status: TaskStatus) -> Self {
        self.status = Some(status);
        self
    }

    pub fn due_at(mut self, due_at: Option<String>) -> Self {
        self.due_at = Some(due_at);
        self
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct User {
    pub id: String,
    pub email: String,
    pub name: String,
    pub password_hash: String,
    pub created_at: String,
    pub updated_at: String,
}

impl User {
    pub fn new(
        id: impl Into<String>,
        email: impl Into<String>,
        name: impl Into<String>,
        password_hash: impl Into<String>,
        created_at: impl Into<String>,
        updated_at: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            email: email.into(),
            name: name.into(),
            password_hash: password_hash.into(),
            created_at: created_at.into(),
            updated_at: updated_at.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Viewer {
    pub id: String,
    pub name: String,
    pub email: String,
}

impl Viewer {
    pub fn new(id: impl Into<String>, name: impl Into<String>, email: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            email: email.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AttachmentDisplay {
    Inline,
    Attached,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldValueType {
    Text,
    Enum,
    Bool,
    Int,
    Decimal,
    List,
    Url,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskStatus {
    Inbox,
    UpNext,
    InProgress,
    Focused,
    Paused,
    Done,
    Archived,
}
